import { FaLeaf } from 'react-icons/fa';
import FacilityDetailLayout from '../components/FacilityDetailLayout';

export default function FacilityEHS() {
    const glob = import.meta.glob('/public/images/facilities/ehs/*.{png,jpg,jpeg,webp}', { eager: true, query: '?url', import: 'default' });
    const galleryImages = Object.values(glob).map(path => path.replace(/^\/public/, ''));

    return (
        <FacilityDetailLayout
            title="Environment, Health & Safety"
            subtitle="Safe · Sustainable · Compliant"
            galleryImages={galleryImages}
            intro="PRADO's Environment, Health & Safety (EHS) department ensures that every aspect of our operations is conducted safely, responsibly, and in full compliance with applicable environmental and occupational safety regulations."
            image="/images/facilities/ehs.png"
            icon={<FaLeaf />}
            // stats={[
            //     { value: '0', label: 'LTI Incidents' },
            //     { value: 'ISO', label: 'Safety Standards' },
            //     { value: '100%', label: 'Staff Trained' },
            //     { value: 'GLP', label: 'EHS Compliance' },
            // ]}
            features={[
                {
                    title: 'Occupational Safety Management',
                    description: 'Comprehensive occupational health and safety programs protecting all staff from physical, chemical, biological, and ergonomic hazards.',
                    bullets: [
                        'Personal protective equipment (PPE) protocols and training',
                        'Chemical handling and laboratory safety training',
                        'Emergency response drills and evacuation procedures',
                        'Incident reporting and investigation system',
                    ]
                },
                {
                    title: 'Biological Safety',
                    description: 'Rigorous biosafety protocols for handling biological samples, pathogens, and animal-derived materials in accordance with biosafety level (BSL) requirements.',
                    bullets: [
                        'Biosafety cabinet certification and maintenance',
                        'Biohazard waste segregation and inactivation',
                        'Zoonosis prevention programs for animal handlers',
                    ]
                },
                {
                    title: 'Chemical Safety & Hazardous Materials',
                    description: 'Full management of chemical inventories, including safety data sheet (SDS) accessibility, hazardous material storage, and spill response protocols.',
                },
                {
                    title: 'Waste Management',
                    description: 'Environmentally responsible management of all waste streams generated by research operations.',
                    bullets: [
                        'Segregated biomedical, chemical, and general waste streams',
                        'Authorized hazardous waste disposal vendors',
                        'Animal carcass incineration in compliance with CCSEA norms',
                    ]
                },
                {
                    title: 'Environmental Monitoring',
                    description: 'Continuous monitoring of air quality, water, and effluent discharges to ensure environmental compliance and protect surrounding communities.',
                },
                {
                    title: 'Safety Training & Culture',
                    description: 'Mandatory induction, annual refresher, and role-specific safety training for all personnel, fostering a culture of proactive safety leadership across the organization.',
                }
            ]}
        >
            <div className="max-w-4xl mx-auto space-y-8 text-lg text-slate-700 dark:text-slate-300 font-light leading-relaxed">
                <p>
                    The Environment, Health & Safety (EHS) department at PRADO manages all aspects of occupational health, biological safety, and environmental protection. We implement rigorous safety protocols to protect our researchers, animal handlers, and the community from chemical, biological, and physical hazards.
                </p>
                <p>
                    Our program includes comprehensive staff training, emergency preparedness, and biosafety cabinet certifications. We are committed to sustainable waste management and environmental monitoring, ensuring that all biomedical and hazardous waste streams are processed in strict compliance with CCSEA and national standards.
                </p>
            </div>
        </FacilityDetailLayout>
    );
}
