import { FaLeaf } from 'react-icons/fa';
import FacilityDetailLayout from '../components/FacilityDetailLayout';

export default function FacilityEHS() {
    const glob = import.meta.glob('/images/facilities/ehs/*.{png,jpg,jpeg,webp}', { eager: true, query: '?url', import: 'default' });
    const galleryImages = Object.values(glob);

    return (
        <FacilityDetailLayout
            title="Environment, Health & Safety"
            subtitle="Safe · Sustainable · Compliant"
            galleryImages={galleryImages}
            intro="PRADO's Environment, Health & Safety (EHS) department ensures that every aspect of our operations is conducted safely, responsibly, and in full compliance with applicable environmental and occupational safety regulations."
            image="/images/img-home-gallery-2.png"
            icon={<FaLeaf />}
            stats={[
                { value: '0', label: 'LTI Incidents' },
                { value: 'ISO', label: 'Safety Standards' },
                { value: '100%', label: 'Staff Trained' },
                { value: 'GLP', label: 'EHS Compliance' },
            ]}
            features={[
                {
                    title: 'Occupational Safety Management',
                    description: 'Comprehensive occupational health and safety programs protecting all staff from physical, chemical, biological, and ergonomic hazards.',
                    bullets: [
                        'Personal protective equipment (PPE) protocols and training',
                        'Chemical handling and laboratory safety training',
                        'Emergency response drills and evacuation procedures',
                        'Incident reporting and investigation system',
                    ]
                },
                {
                    title: 'Biological Safety',
                    description: 'Rigorous biosafety protocols for handling biological samples, pathogens, and animal-derived materials in accordance with biosafety level (BSL) requirements.',
                    bullets: [
                        'Biosafety cabinet certification and maintenance',
                        'Biohazard waste segregation and inactivation',
                        'Zoonosis prevention programs for animal handlers',
                    ]
                },
                {
                    title: 'Chemical Safety & Hazardous Materials',
                    description: 'Full management of chemical inventories, including safety data sheet (SDS) accessibility, hazardous material storage, and spill response protocols.',
                },
                {
                    title: 'Waste Management',
                    description: 'Environmentally responsible management of all waste streams generated by research operations.',
                    bullets: [
                        'Segregated biomedical, chemical, and general waste streams',
                        'Authorized hazardous waste disposal vendors',
                        'Animal carcass incineration in compliance with CPCSEA norms',
                    ]
                },
                {
                    title: 'Environmental Monitoring',
                    description: 'Continuous monitoring of air quality, water, and effluent discharges to ensure environmental compliance and protect surrounding communities.',
                },
                {
                    title: 'Safety Training & Culture',
                    description: 'Mandatory induction, annual refresher, and role-specific safety training for all personnel, fostering a culture of proactive safety leadership across the organization.',
                }
            ]}
        />
    );
}
